server:
  port: 8080

spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: sensor-service
  datasource:
    url: jdbc:postgresql://${HOST_SENSOR}/${POSTGRES_DB}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
security:
  jwt:
    secret: ${JWT_SECRET}
    access-duration: ${JWT_ACCESS_DURATION}
    refresh-duration: ${JWT_REFRESH_DURATION}